include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enable recommended lints
    - prefer_const_constructors
    - prefer_final_fields
    - avoid_print
    - prefer_single_quotes
    - sort_pub_dependencies
    - cancel_subscriptions
    - close_sinks
    
analyzer:
  errors:
    unused_import: error
    unused_variable: info
    unused_field: warning
    prefer_const_constructors: info
    avoid_print: warning
