// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABmSehZad0iDMLWGIaF-d82_IcL_kxLFs',
    appId: '1:9849806606:web:2def425ca5ab1b2f78c15f',
    messagingSenderId: '9849806606',
    projectId: 'game26-base',
    authDomain: 'game26-base.firebaseapp.com',
    storageBucket: 'game26-base.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqXj_JAFMBrwc5gmgkoqFVqJ7_-1R2z6Q',
    appId: '1:9849806606:android:7373d55a29ac6f6b78c15f',
    messagingSenderId: '9849806606',
    projectId: 'game26-base',
    storageBucket: 'game26-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGQafk6UdgBoaqNUkPtVteb0mxKfiFOOo',
    appId: '1:9849806606:ios:4fd19d3613aa6bde78c15f',
    messagingSenderId: '9849806606',
    projectId: 'game26-base',
    storageBucket: 'game26-base.firebasestorage.app',
    iosBundleId: 'com.example.bcgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGQafk6UdgBoaqNUkPtVteb0mxKfiFOOo',
    appId: '1:9849806606:ios:4fd19d3613aa6bde78c15f',
    messagingSenderId: '9849806606',
    projectId: 'game26-base',
    storageBucket: 'game26-base.firebasestorage.app',
    iosBundleId: 'com.example.bcgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABmSehZad0iDMLWGIaF-d82_IcL_kxLFs',
    appId: '1:9849806606:web:6d779b5af912fe9b78c15f',
    messagingSenderId: '9849806606',
    projectId: 'game26-base',
    authDomain: 'game26-base.firebaseapp.com',
    storageBucket: 'game26-base.firebasestorage.app',
  );

}